CREATE TABLE "config"."procedures_parameters" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "type" int NOT NULL,
  "type_parameters" varchar NOT NULL,
  "index" int NOT NULL,
  "id_procedures" int NOT NULL,
  	CONSTRAINT procedures_in_fk1 FOREIGN KEY (id_procedures) REFERENCES config."procedures"(id)
);

COMMENT ON TABLE "config"."procedures_parameters" IS 'Таблица для указания входящих параметров в хранимые процедуры';

COMMENT ON COLUMN config.procedures_parameters.id IS 'Первичный ключ';
COMMENT ON COLUMN config.procedures_parameters."name" IS 'Имя параметра';
COMMENT ON COLUMN config.procedures_parameters."type" IS 'Тип параметра (значение)';
COMMENT ON COLUMN config.procedures_parameters."type_parameters" IS 'Тип параметра (хранимой процедуры: in, out)';
COMMENT ON COLUMN config.procedures_parameters."index" IS 'Индекс параметра';
COMMENT ON COLUMN config.procedures_parameters."id_procedures" IS 'Внешний ключ процедуры';
