CREATE TABLE "teaching"."institution_specialization" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "specialization_id" int NOT NULL,
  "institution_id" int NOT NULL
); 
ALTER TABLE "teaching"."institution_specialization" ADD FOREIGN KEY ("specialization_id") REFERENCES "teaching"."specialization" ("id");
ALTER TABLE "teaching"."institution_specialization" ADD FOREIGN KEY ("institution_id") REFERENCES "teaching"."institution" ("id");
