CREATE TABLE "libs"."city" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_area" int,
  "name" varchar UNIQUE NOT NULL
);

ALTER TABLE "libs"."city" ADD FOREIGN KEY ("id_area") REFERENCES "libs"."area" ("id");
