CREATE TABLE "teaching"."institution" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_city" int NOT NULL,
  "name" varchar UNIQUE NOT NULL,
  "address" varchar NOT NULL,
  "description" text NOT NULL,
  "tlf" varchar NOT NULL,
  "date_of_foundation" date NOT NULL,
  "active" boolean DEFAULT false
);
ALTER TABLE "teaching"."institution" ADD FOREIGN KEY ("id_city") REFERENCES "libs"."city" ("id");
