CREATE TABLE "teaching"."specialization" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "code" varchar NOT NULL,
  "name" varchar NOT NULL,
  "description" text,
  "term" int NOT NULL
);